spring:
  datasource:
    url: jdbc:postgresql://db.osgfwgedjdltrmvwycjd.supabase.co:5432/postgres
    username: postgres
    password: ${DB_PASSWORD:Branco2025.}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080
  servlet:
    context-path: /api/v1

dc3:
  template: templates/DC3_Oficial.docx
  output: C:/NAF/DC3/
  company:
    name: NORTH AMERICA FLOORING SA DE CV
    rfc: NAF000000XXX
    representative: JINSONG ZHAO
    workersRepresentative: LILIANA ROSALES
